# Generated by Django 3.2.5 on 2022-07-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripnew',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(default=0, max_length=255)),
                ('headsign', models.CharField(default=0, max_length=50)),
                ('direction', models.PositiveIntegerField(default=0)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
            options={
                'db_table': 'tripsnew',
            },
        ),
    ]
