# Generated by Django 3.2.5 on 2022-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tripnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripnew',
            name='headsign',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
