# Generated by Django 3.2.5 on 2022-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('content', models.TextField()),
                ('reply', models.TextField()),
                ('creat_time', models.TextField(default='')),
                ('reply_time', models.TextField(default='')),
                ('reply_email', models.TextField(default='')),
            ],
        ),
    ]
